while True:
    file_name = input('Enter a file name: ')
    if file_name.endswith('EXIT'):
        print("Goodbye!");
        break
    elif file_name.endswith(".py"): print("It is a PYTHON File")
    elif file_name.endswith(".html"): print("It is a HTML File")
    elif file_name.endswith(".pdf"): print("It is a PDF File")
    elif file_name.endswith(".jpg"): print("It is an IMAGE File")
    elif file_name.endswith(".mp3"): print("It is an AUDIO File")
    elif file_name.endswith(".mp4"): print("It is a VIDEO File")
    elif file_name.endswith(".c"): print("It is a C File")
    elif file_name.endswith(".css"): print("It is a CSS File")
    elif file_name.endswith(".js"): print("It is a Python File")
    elif file_name.endswith(".png"): print("It is an IMAGE File")
    elif file_name.endswith(".mkv"): print("It is a VIDEO File")
    elif file_name.endswith(".mpg"): print("It is a VIDEO File")
    elif file_name.endswith(".avi"): print("It is a VIDEO File")
    elif file_name.endswith(".zip"): print("It is a ZIP File")
    elif file_name.endswith(".rar"): print("It is a RAR File")
    elif file_name.endswith(".tar"): print("It is a TAR File")
    elif file_name.endswith(".gz"): print("It is a GZIP File")
    elif file_name.endswith(".bz2"): print("It is a BZIP2 File")
    elif file_name.endswith(".7z"): print("It is a 7ZIP File")
    elif file_name.endswith(".iso"): print("It is a ISO File")
    elif file_name.endswith(".apk"): print("It is an APK File")
    elif file_name.endswith(".jar"): print("It is a JAR File")
    elif file_name.endswith(".java"): print("It is a JAVA File")
    elif file_name.endswith(".class"): print("It is a CLASS File")
    elif file_name.endswith(".cpp"): print("It is a C++ File")
    elif file_name.endswith(".cs"): print("It is a C# File")
    elif file_name.endswith(".php"): print("It is a PHP File")
    elif file_name.endswith(".pyc"): print("It is a PYC File")
    elif file_name.endswith(".pyw"): print("It is a PYW File")
    elif file_name.endswith(".rb"): print("It is a RB File")
    elif file_name.endswith(".pl"): print("It is a PL File")
    elif file_name.endswith(".sh"): print("It is a SH File")
    elif file_name.endswith(".bat"): print("It is a BAT File")
    elif file_name.endswith(".vb"): print("It is a VB File")
    elif file_name.endswith(".vbs"): print("It is a VBS File")
    elif file_name.endswith(".txt"): print("It is a TEXT file")
    elif file_name.endswith(".log"): print("It is a LOG File")
    elif file_name.endswith(".ini"): print("It is a INI File")
    elif file_name.endswith(".xml"): print("It is a XML File")
    elif file_name.endswith(".json"): print("It is a JSON File")
    elif file_name.endswith(".sql"): print("It is a SQL File")
    elif file_name.endswith(".md"): print("It is a MARKDOWN File")
    elif file_name.endswith(".docx"): print("It is a WORD DOCUMENT File")
    elif file_name.endswith(".xlsx"): print("It is a EXCEL File")
    elif file_name.endswith(".pptx"): print("It is a POWER POINT File")
    elif file_name.endswith(".csv"): print("It is a CSV File")
    elif file_name.endswith(".rtf"): print("It is a RTF File")
    elif file_name.endswith(".odt"): print("It is a ODT File")
    elif file_name.endswith(".ods"): print("It is a ODS File")
    elif file_name.endswith(".odp"): print("It is a ODP File")
    elif file_name.endswith(".odg"): print("It is a ODG File")
    elif file_name.endswith(".odf"): print("It is a ODF File")
    elif file_name.endswith(".odb"): print("It is a ODB File")
    elif file_name.endswith(".odc"): print("It is a ODC File")
    elif file_name.endswith(".odm"): print("It is a ODM File")
    elif file_name.endswith(".ott"): print("It is a OTT File")
    elif file_name.endswith(".ots"): print("It is a OTS File")
    elif file_name.endswith(".otp"): print("It is a OTP File")
    elif file_name.endswith(".otg"): print("It is a OTG File")
    elif file_name.endswith(".oth"): print("It is a OTH File")
    elif file_name.endswith(".exe"): print("It is an EXECUTABLE File")
    elif file_name.endswith(".msi"): print("It is a MSI File")
    elif file_name.endswith(".msp"): print("It is a MSP File")
    elif file_name.endswith(".msc"): print("It is a MSC File")
    elif file_name.endswith(".msh"): print("It is a MSH File")
    elif file_name.endswith(".msh1"): print("It is a MSH1 File")
    else: print("It is a UNKNOWN File")
    # Created by Vedansh Dubey.